### ISSUE TITLE
Metastream errors on launch when missing VC++ dependency

### ISSUE THREAD

**Issue by samuelmaddock** [samuelmaddock/metastream#14]
- Metastream Version: 0.1.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open Metastream without Visual C++ dependencies.

```
Error: The specified module could not be found.
```

![chrome_2018-09-16_03-14-16g3sv](https://user-images.githubusercontent.com/1656324/45593909-a4568c80-b95e-11e8-9bb9-6df54caa3862.png)

To fix this, the user needs to install Visual C++ Redistributable for Visual Studio 2015
https://www.microsoft.com/en-us/download/details.aspx?id=48145

This error should be caught on startup and a dialog should instruct the user to download this.

**Comment by samuelmaddock** [comment]
Should be fixed by 1d53c0a8e6db064292dafd1c56c8b3af80f63714, I wasn't able to test though as I had issues trying to uninstall the dependencies.

I'll re-open if someone reports this again after the release of v0.1.4.

**Comment by samuelmaddock** [comment]
Oops, I forgot to update the download links on the website so people were still downloading 0.1.3 without the friendly error message. 😭

**Comment by talynone** [comment]
Bug still exists in 0.14, friend who lives in NZ running Windows 10 latest x64 had the startup error, was fixed by installing x64 C++ redistributable from Microsoft.

**Comment by samuelmaddock** [comment]
@talynone Does your friend use a language other than English on Windows? I was checking explicitly for English text previously. This will be fixed in the next update. e2afdca9336cb7abe5df170f08b73369d5baa20b

**Comment by talynone** [comment]
Sorry for the delayed response, she's using English, I'm not sure if she's using a New Zealand / Australian / British variant though.

**Comment by samuelmaddock** [comment]
Closing as the Electron app will soon be deprecated by #94.
